### ISSUE TITLE
Do you accept Pull Requests?

### ISSUE THREAD

**Issue by grandeljay** [arielhr1987/leira-roles#3]
Hey there,

I've been using this plugin for a couple of years now and think it's perfect! It seems to be getting slightly outdated. If I made some changes to the code style (to match WordPress's style) and maybe updated the README to update that it's still compatible with newer versions of WordPress, would you review them and consider merging them?

**Comment by arielhr1987** [comment]
Hi @grandeljay 
For sure, any help with the plugin is welcome.
Feel free to create any PR with the changes you suggest

**Comment by grandeljay** [comment]
Neat, thanks! I opened two in 2021, can you start with those please?

**Comment by arielhr1987** [comment]
Puff, i never saw those PRs :(, sorry about that.
Working on it...

**Comment by arielhr1987** [comment]
Merged!
@grandeljay can you share your wp user to include you to contributors section?

**Comment by grandeljay** [comment]
Sure, my WordPress username is the same as in GitHub: [grandeljay](https://profiles.wordpress.org/grandeljay/)

Thank you!

**Comment by arielhr1987** [comment]
@grandeljay I prepared all code to make a new plugin release (version 1.1.9) in master branch. I checked everything locally, and seems to work ok. Please check it as well, to release it to WP. Thanks, in advance.

**Comment by grandeljay** [comment]
Neat! Everything looks good to me too.

I just noticed that there is some padding missing where the capabilities can be selected
![image](https://github.com/arielhr1987/leira-roles/assets/45571053/f89fd953-c145-480f-809c-7285766d7b6b)

I have never worked with SCSS though, would you mind adding some build instructions to the README so I can suggest a pull request for this?

**Comment by arielhr1987** [comment]
Great!

Actually I added that padding in my last commit, maybe clearing your cache fixes the problem.

Regarding SCSS, I simply use the file watcher option in [PhpStorm](https://www.jetbrains.com/help/phpstorm/transpiling-sass-less-and-scss-to-css.html#ws_sass_less_scss_example_scss
)
But it think is better to use a development environment like wp-env for easy dev setup

**Comment by arielhr1987** [comment]
Version 1.1.9 released!
